# Generated by Django 6.1.1 on 2026-09-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProduceBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('crop_name', models.CharField(choices=[('Tomato', 'Tomato'), ('Paddy', 'Paddy'), ('Chilli', 'Chilli'), ('Cotton', 'Cotton'), ('Mango', 'Mango'), ('Groundnut', 'Groundnut')], max_length=100)),
                ('quantity', models.FloatField()),
                ('harvest_date', models.DateField()),
                ('temperature', models.FloatField(default=8.0)),
                ('humidity', models.FloatField(default=65.0)),
                ('quality_score', models.FloatField(default=100)),
                ('shelf_life', models.FloatField(default=7)),
                ('wastage_risk', models.FloatField(default=5)),
                ('status', models.CharField(choices=[('Healthy', 'Healthy'), ('Attention', 'Attention'), ('Critical', 'Critical')], default='Healthy', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
