# Generated by Django 6.1.1 on 2026-09-10 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(default='Normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=150)),
                ('season', models.CharField(choices=[('Kharif', 'Kharif'), ('Rabi', 'Rabi'), ('Zaid', 'Zaid'), ('Year Round', 'Year Round')], max_length=30)),
                ('water_requirement', models.CharField(blank=True, max_length=100)),
                ('soil_type', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='crops/')),
            ],
        ),
        migrations.CreateModel(
            name='CropCultivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sowing_date', models.DateField()),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_yield', models.DecimalField(blank=True, decimal_places=2, help_text='Expected yield in kg', max_digits=10, null=True)),
                ('status', models.CharField(default='Growing', max_length=50)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivations', to='core.crop')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='disease_scans/')),
                ('detected_disease', models.CharField(blank=True, max_length=200)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('treatment', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_detections', to='core.crop')),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=200)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('soil_type', models.CharField(blank=True, max_length=100)),
                ('irrigation_type', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('village', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(default='Andhra Pradesh', max_length=100)),
                ('land_area', models.DecimalField(decimal_places=2, help_text='Land area in acres', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=100)),
                ('minimum_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maximum_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_date', models.DateField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_prices', to='core.crop')),
            ],
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity in kg', max_digits=12)),
                ('quality', models.CharField(choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C')], max_length=1)),
                ('harvest_date', models.DateField()),
                ('expected_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available_for_sale', models.BooleanField(default=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce', to='core.crop')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce', to='core.farmerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rainfall', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('wind_speed', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ProduceBatch',
        ),
        migrations.AddField(
            model_name='advisory',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisories', to='core.crop'),
        ),
        migrations.AddField(
            model_name='cropcultivation',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivations', to='core.farm'),
        ),
        migrations.AddField(
            model_name='farm',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='core.farmerprofile'),
        ),
        migrations.AddField(
            model_name='diseasedetection',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_detections', to='core.farmerprofile'),
        ),
    ]
